### ISSUE TITLE
Symlinking to `/usr/local/bin` instead of modifying $PATH

### ISSUE THREAD

**Issue by bucaran** [yyuu/pyenv#319]
> Note: If you are on a mac and use homebrew, chances are you already own `/usr/local/`, so the following installation method should not require `sudo`. It does if you do not own `/usr/local/`.

```bash
git clone https://github.com/yyuu/pyenv.git .pyenv
echo 'export PYENV_ROOT="$HOME/.pyenv"' >> $HOME/.bash_profile
ln -s $HOME/.pyenv/bin/pyenv /usr/local/bin
pyenv init
```
I prefer `.profile` instead BTW, but it's up to you.

Let me know if you spot anything strange in the script above.

**Comment by blueyed** [comment]
> ln -s $HOME/.pyenv/bin/pyenv /usr/local/bin

I would make it more explicit by also specifying the target filename.

Also make sure to be in $HOME, or use ~/.pyenv when cloning.

**Comment by yyuu** [comment]
You can create symlink of `pyenv` into `/usr/local/bin`. It's your choice. I don't like it, though. I believe, pyenv isn't just for OS X, and `/usr/local` isn't just for `$USER`.

**Comment by bucaran** [comment]
@yyuu So, who is it for? Multiple users like in the 60s?

**Comment by yyuu** [comment]
I'm developing pyenv mainly just for my curious, and for the people who
are contributing to this project.

Sharing a machine with multiple users is still very common on servers in
this 2010's, and I'm using pyenv mainly on Debian GNU/Linux.
Its '/usr/local/bin' isn't writable from normal users by default.

I'd like to improve interoperability to OS X since I'm using it as well,
but it isn't everything for me. Again, the users of pyenv have options to
install pyenv in '/usr/local/bin' and it'll work properly. Although, I'd
not recommend it as the default installation method to keep
interoperability to other Unix variants.


-- 
山下 優 (やました ゆう)
peek824545201@gmail.com

**Comment by bucaran** [comment]
I don't know if I would say _still very common_, but yeah, it's definitely not unheard of. 

So what do you recommend?

**Comment by jhermann** [comment]
Probe /usr/local/bin for being owned by your current (non-root) user, and if yes, you could go ahead with the symlink, since ownership is a strong indicator towards the different policy.

**Comment by bucaran** [comment]
In my case, I `chown`ed me `/usr/local/bin` for a simpler life and I lived happily ever after. So, basically, I keep my stuff in `$HOME` and symlink to `/usr/local/bin`. 

Now, what do you guys recommend instead? Or rather, what is your setup?

Cheers
