### ISSUE TITLE
pyenv's pip placing src/ in wrong directory

### ISSUE THREAD

**Issue by mcandre** [yyuu/pyenv#406]
When I use pyenv's pip to install some dependencies from source, pip creates a `./src/` directory clashing with my current working project/directory, rather than a better location such as `~/.pyenv/src/`. Am I doing something wrong?

Trace:

```
myproject$ ls src
ls: cannot access src: No such file or directory
myproject$ pip install -r requirements.txt
...
myproject$ ls src
...
```

Ordinarily, I would gitignore this directory, but `src/` is so commonly used to hold first party code in version controlled project structures, that it's bad form to do this.

Configuration:

https://github.com/mcandre/dotfiles/blob/master/.bashrc.d/pyenv.sh

https://github.com/mcandre/dotfiles/blob/master/.python-version

System:

```
pyenv --version
pyenv 20150601
```

Mac OS X 10.10.4

**Comment by joshfriend** [comment]
Can you list the packages you are trying to install? Perhaps one of these is trying to write to a `src/` folder.

**Comment by mcandre** [comment]
Dependencies (all git-sourced):

* https://github.com/Doist/hash_ring
* https://github.com/leifker/SpiffWorkflow
* https://github.com/mumrah/kafka-python
* https://github.com/seajosh/python-instagram

However, my coworkers suggest that virtualenv does not have the `src/` folder creation issue, only pyenv.

**Comment by blueyed** [comment]
Can you provide the contents of requirements.txt?
Is there something to be installed editable in there? (`-e`)

See the `--src` option for `pip install`, where you could use another directory.

    --src <dir>  Directory to check out editable projects into. The
                 default in a virtualenv is "<venv path>/src". The
                 default for global installs is "<current dir>/src".

**Comment by mcandre** [comment]
Thanks for the tip! Yes, `-e` editable is used. I might remove it for now.

I assume the 'global' default applies to pyenv contexts. Would it make sense to encourage pip to make the default `~/.pyenv/src` for pyenv contexts?

**Comment by yyuu** [comment]
It is because pip handles only virtualenvs differently. I don't think this is an issue of pyenv, would be an issue of pip`.

https://github.com/pypa/pip/blob/685c8b5ace6aaac7bf8c2c0269a9adb95e17a6ad/pip/cmdoptions.py#L373-L382
https://github.com/pypa/pip/blob/685c8b5ace6aaac7bf8c2c0269a9adb95e17a6ad/pip/locations.py#L105-L115

Basically I think the user of `pip` should specify `--src` explicitly if s?he wants to install the library to custom destination. I don't want to have something like `~/.pyenv/src` since everything in pyenv is basically editable.
