### ISSUE TITLE
python-build 3.5-dev definition points to BitBucket mirror of CPython source, which has been stale for 2+ months

### ISSUE THREAD

**Issue by BanzaiMan** [yyuu/pyenv#409]
The last update on https://bitbucket.org/mirror/cpython is 2015-05-07, 2+ months ago. https://hg.python.org/cpython/ shows active development.

Is there a reason to prefer BitBucket mirror to the canonical repository?

An obvious change is:

```diff
diff --git a/plugins/python-build/share/python-build/3.5-dev b/plugins/python-build/share/python-build/3.5-dev
index 530f93b..a4d44ff 100644
--- a/plugins/python-build/share/python-build/3.5-dev
+++ b/plugins/python-build/share/python-build/3.5-dev
@@ -1,3 +1,3 @@
 #require_gcc
 install_package "readline-6.3" "http://ftpmirror.gnu.org/readline/readline-6.3.tar.gz#56ba6071b9462f980c5a72ab0023893b65ba6debb4eeb475d7a563dc65cafd43" standard --if has_broken_mac_readline
-install_hg "Python-3.5-dev" "https://bitbucket.org/mirror/cpython" "default" standard verify_py35 ensurepip
+install_hg "Python-3.5-dev" "https://hg.python.org/cpython/" "default" standard verify_py35 ensurepip
```

which currently (https://hg.python.org/cpython/rev/2854dba70ee7) leads to failure: https://gist.github.com/BanzaiMan/e59b9a2ec5d023c58d69 although I am not sure if this is an issue with python-build or not.

**Comment by alex** [comment]
This looks sensible to me -- does anyone recall why bitbucket was chosen in the first place?

**Comment by joshfriend** [comment]
Another thought: Why check out the whole history (which is very large), when you could install [`tip.tar.bz2`](https://hg.python.org/cpython/archive/tip.tar.bz2) instead?

**Comment by yyuu** [comment]
@BanzaiMan @alex 
I configured to cline from bitbucket since its bandwidth seems faster than hg.python.org at the time of writing the feature. I think it should be replaced by hg.python.org if the mirror isn't working now. Please  create PR from your patch.

@joshfriend 
Cloning hg repo is much bigger than source tarball, but I think it is not a problem if there's ~/.pyenv/cache. I think it would be better to use source repo than tarball for installing from development HEAD.
