### ISSUE TITLE
Set system python and custom python3

### ISSUE THREAD

**Issue by pohmelie** [yyuu/pyenv#442]
Ubuntu 14.04
```
[poh ~]$ pyenv versions
* system (set by /home/poh/.pyenv/version)
  2.7.10
  3.4.3
  3.5.0
[poh ~]$ python3 --version
Python 3.4.1
[poh ~]$ pyenv global system 3.4.3
[poh ~]$ python3 --version
Python 3.4.1
[poh ~]$ pyenv versions
* system (set by /home/poh/.pyenv/version)
  2.7.10
* 3.4.3 (set by /home/poh/.pyenv/version)
  3.5.0
```

**Comment by yyuu** [comment]
What's your point? It looks nothing wrong for me.

**Comment by pohmelie** [comment]
I want "python" system and "python3" 3.4.3

**Comment by yyuu** [comment]
If so, you don't have to put system at the top of versions.  'pyenv global 3.4.3 system' should solve.

**Comment by pohmelie** [comment]
No, this does not.
```
[poh ~]$ pyenv global 3.4.3 system
[poh ~]$ python --version
Python 3.4.3
[poh ~]$ python3 --version
Python 3.4.3
```

**Comment by blueyed** [comment]
You could use "python2" explicitly, but that's likely not what you want.

Re-opening for now.

**Comment by pohmelie** [comment]
@blueyed exactly.

**Comment by yyuu** [comment]
I was really frustrated with fire-and-forget non-bug opened issues. Sorry I didn't get what you meant.

This is expected behaviour with current impl of pyenv at least for now. `python` is the special name in pyenv which always points to the executable of python interpreter of first activated version.

If you want to switch versions with using `python` executable, you need to switch version per invocation. (using the `PYENV_VERSION` would be the easiest)

```sh
$ pyenv versions
* system (set by /home/poh/.pyenv/version)
  2.7.10
  3.4.3
  3.5.0
$ env PYENV_VERSION=system python --version
Python 3.4.1
$ env PYENV_VERSION=3.4.3 python --version
Python 3.4.3
```

**Comment by pohmelie** [comment]
Ok, thanks for answer! I think this solution is good for me.
