### ISSUE TITLE
Tox usage with pyenv local

### ISSUE THREAD

**Issue by shulhi** [yyuu/pyenv#466]
So I've set `pyenv global 3.5.0 3.4.3 2.7.8` and this works well if I'm outside any project that has python version locally defined using `.python-version`. This causes issue when running `tox` for project that has `.python-version` defined.

For example:

Outside project with no pyenv local set, I can do:
```
$ python --version
Python 3.5.0

$ python3.4 --version
Python 3.4.3

$ python2.7 --version
Python 2.7.8
```

Now, if I'm inside a project with pyenv locally set (having `.python-version`) like so,

```
$ pyenv virtualenv 2.7.8 my-project
$ pyenv local my-project
(my-project) $ python3.5 --version
pyenv: python3.5: command not found

The `python3.5' command exists in these Python versions:
  3.5.0
```

Is this by design or am I doing something wrong? Due to this, I can't run `tox` with project that has `.python-version` defined.

**Comment by yyuu** [comment]
Basically it is by design. If you'd like to usemultiple versions at once, you need to specify versions in some source (e.g. global, local or shell).

If your project has .python-version (local) in its repository, you can override the configuration with using 'pyenv shell' (or PYENV_VERSION envairoment variable) sice shell is the most favable in pyenv. Writing some wrapper script to run tox would work for your project.
