### ISSUE TITLE
python-build failing to install openssl

### ISSUE THREAD

**Issue by pdarragh** [yyuu/pyenv#482]
I'm attempting to deploy a system-wide Python 3.5.0 via `python-build 3.5.0 /usr/local/`, but it fails and this is the output:

```
# python-build 3.5.0 /usr/local/
Downloading openssl-1.0.1p.tar.gz...
-> https://yyuu.github.io/pythons/bd5ee6803165c0fb60bbecbacacf244f1f90d2aa0d71353af610c29121e9b2f1
Installing openssl-1.0.1p...

BUILD FAILED (OS X 10.10.5 using python-build 20151105-4-g9ca7de5)

Inspect or clean up the working tree at /tmp/python-build.20151117114931.27783
Results logged to /tmp/python-build.20151117114931.27783.log

Last 10 log lines:
installing man7/des_modes.7
installing man3/dh.3
installing man3/dsa.3
installing man3/ecdsa.3
installing man3/engine.3
installing man3/err.3
installing man3/evp.3
installing man3/hmac.3
/bin/sh: /usr/local//openssl/ssl/man/man3/hmac.3: Too many levels of symbolic links
make: *** [install_docs] Error 1
```

This may be a problem specific to my environment (enterprise deployment), and it may be an OpenSSL issue, but I figured I'd start here in case you've seen this. I don't see the same issues with a per-user installation (`pyenv install 3.5.0` works just fine). Any ideas?

**Comment by yyuu** [comment]
> /bin/sh: /usr/local//openssl/ssl/man/man3/hmac.3: Too many levels of symbolic links

Probably you'd have looping symlink at `/usr/local/openssl/ssl/man/man3/hmac.3`. I'd recommend you to specify dedicated directory as the prefix per versions, instead of installing everything in `/usr/local`. If you'd like to install everything in `/usr/local`, it might be better to install CPython simply with `./configure && make && make install`. This must not be a pyenv issue anyways.
