### ISSUE TITLE
Failing at loading automatically pyenv (OS X 10.10.5)

### ISSUE THREAD

**Issue by politicus** [yyuu/pyenv#500]
I appended my .zshrc file with eval "$(pyenv init -)" and every time I launch iterm I still have: 

Load pyenv automatically by appending the following to ~/.zshrc

**Comment by yyuu** [comment]
I couldn't get what you meant. Basically .zshrc is for all shell interactive sessions and it should be loaded automatically into every shell.

**Comment by politicus** [comment]
When I try the command "pyenv init" (bash or zsh) I get the message Load pyenv automatically by appending the following to .bash_profile or .zshrc. 

The problem is I already added this line of code to .bash_profile and .zshrc.

**Comment by yyuu** [comment]
Probably you have 'eval "$(pyenv init)"' somewhere in your shell configuration. Please fix it as 'eval "$(pyenv init -)"'. Trailing '-' is the key.

**Comment by politicus** [comment]
I installed pyenv via hombrew. Once it was installed I followed the documentation's intructions and issued  the command pyenv init. I did nothing else. How can I have eval "$(pyenv init)"' somewhere in my shell configuration?  In whiwh file? I checked etc/profile etc/paths. Everyhting is fine. Reinstalled pyenv via Homebrew same problem again. I checked I added a '-' in my .zshrc file.

**Comment by yyuu** [comment]
Installation source isn't a matter. It will only appear if you have missing somewhere in your shell configuration by definition. I don't know configuration of your system, though.

https://github.com/yyuu/pyenv/blob/master/libexec/pyenv-init#L45

**Comment by rschwiebert** [comment]
I installed pyenv and pyenv-virtualenv with HomeBrew and the instructions in the docs here. I can't seem to get the automatic sourcing to work either.

I have these in my bash_profile, because they appeared at the end of the homebrew messages:

```
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

```
I've also set PYENV_ROOT and put it in PATH in the bash_profile.

The version was created in the `pyenv versions` list and it works just fine if I activate it manually, but it won't activate automatically when I cd into the directory of the same name as the environment.

What ingredient am I missing here? Why won't it fire up the environment?
