### ISSUE TITLE
Build fails for 2.5.6

### ISSUE THREAD

**Issue by chosenken** [yyuu/pyenv#505]
Hi.  I'm attempting to build python 2.5.6 on Ubuntu 14.04.  Specifically I am trying to build it in a docker container from the docker images onmodulus/build-base.  I have uploaded the error log to a gist, and it looks like an issue in readline.c.

https://gist.github.com/anonymous/7246dc6c5dab5b10baf2#L842

**Comment by yyuu** [comment]
IIRC readline isn't a requirement in pyenv. And, I suspect you forgot to capture stderr in the gist.

**Comment by chosenken** [comment]
This is the command that I ran to install pyenv and then try and install python 2.5.6.

```
apt-get update && \
apt-get install -y python-dev libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev libpq-dev llvm && \
curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash && \
export PATH="$HOME/.pyenv/bin:$PATH" && \
eval "$(pyenv init -)" && \
eval "$(pyenv virtualenv-init -)" && \
mkdir -p /mnt/home && \
export MAKEFLAGS="-j $(grep -c ^processor /proc/cpuinfo)" && \
pyenv install 2.5.6
```

You can run the command in a docker container using the following command (its what I ran it in)
```docker run -it --rm onmodulus/build-base bash```

Here is the gist of the output from the command.  https://gist.github.com/f9f0914bde783cf39225

And here is the gist of the log file.  https://gist.github.com/anonymous/f9f0914bde783cf39225

**Comment by yyuu** [comment]
Is the build of 2.5.6 actually failed? I couldn't find any lines of failure message from your gist. I also confirmed that the build of 2.5.6 succeeded on latest Debian sid.

As you mentioned, it seems there's error in `readline`. But the build failure of readline should not make the entire build failed in python-build.

https://github.com/yyuu/pyenv/blob/d6e0120cc86f4e3bc8f2901d994ca75c85bfd06b/plugins/python-build/bin/python-build#L1516

I know there's a build issue of `readline` module of older CPython with GNU Readline 6.3+. Though I don't want to maintain patches for them since `readline` isn't a requirement for `python-build`.

**Comment by yyuu** [comment]
I confirmed that the build success of 2.5.6 on Ubuntu 14.04 with the following Dockerfile.

```
FROM ubuntu:14.04
ENV DEBIAN_FRONTEND "noninteractive"
RUN apt-get update
RUN apt-get --yes install build-essential curl git libbz2-dev libncurses5-dev libreadline-dev libsqlite3-dev libssl-dev make zlib1g-dev
ENV PYENV_ROOT /pyenv
ENV PATH /pyenv/shims:/pyenv/bin:/sbin:/usr/sbin:/bin:/usr/bin
RUN git clone https://github.com/yyuu/pyenv.git /pyenv
RUN pyenv install -v 2.5.6
```

I suspect there might be some build issue with LLVM in 2.5.6.,I'm not sure, though.
