### ISSUE TITLE
Is there any way to cache the installed python version for multi-user environment?

### ISSUE THREAD

**Issue by minhoryang** [yyuu/pyenv#551]
Is there any way to cache installed python version for multi-user environment?

**Comment by yyuu** [comment]
@minhoryang What does `cache` mean in your question? Basically I don't recommend you to share built Python installations since there're hardcoded paths in scripts and executables. Just copying the built Python to different path will make it corrupted.

**Comment by wadkar** [comment]
How would you go about recreating python environment (including virtualenv) on a remote machine? What files I could commit in git history so that a remote developer (assume sufficient competency with pyenv) can recreate the python environment on a remote machine for development?

**Comment by wadkar** [comment]
I think it would be great if we had a small _HOWTO_ in wiki or README.md about recreating pyenv. For example, the tutorial could start with an empty directory and pynev (and other plugins like pyenv-virtualenv if necessary) and shows how the same development environment can be recreated on another machine.
I would be more than happy to write one later (mid-May) if I you could help me with the _magic incantations_ :)

**Comment by brbsix** [comment]
I think it would help to have a better understanding of your use-case. Are you trying bundle a Python installation with a package for an end-user, so they don't need to have Python installed in order to use the application? Or are you trying to share a consistent development environment with other users? I think you're going to have a lot of issues using git for this task. Git doesn't even store permissions correctly.

If you're trying to do the latter (share a dev environment), Vagrant is well-suited for the task. You can start with a Debian or Ubuntu base, install pyenv and everything exactly how you'd like, then package it and share it on the Atlas repo. That will be the easiest option. If you don't need an entire ~500mb Debian/Ubuntu base, with a little more work you may be able to set it up on an Alpine base.

**Comment by wadkar** [comment]
@brbsix 
thanks for chiming in!
Of course, I am not suggesting to commit any `pyenv` files or directories. I am merely curious how to recreate python environment? The simplest use case is when you are starting on a new machine and want to develop a python codebase. The past you is asking what information you need about python version (and perhaps virtualenv) that will help you start up and running.

Assume basic setup without vagrant/docker

**Comment by wadkar** [comment]
Okay, so basically I keep a list of required modules in `requirements.txt` and then create a virtualenv for the project and do `pip install -r requirements.txt`, that's it?
Any pointers/guides on this?
@yyuu : feel free to close the issue if this seems out of scope of pyenv :)
