### ISSUE TITLE
How can I skip the download step?

### ISSUE THREAD

**Issue by ironicChen** [yyuu/pyenv#563]
I want to install a version with the source file instead of downloading when use "pyenv install".

**Comment by yyuu** [comment]
mkdir -p $(puenv root)/cache

**Comment by ironicChen** [comment]
It dosen't work.....

[root@cnsz22vl0279:/root/.pyenv/versions]#ll $(pyenv root)/cache
total 19100
-rw-r--r-- 1 root root 19554643 Mar 28 14:23 Python-3.4.3.tgz

[root@cnsz22vl0279:/root/.pyenv/versions]#pyenv install 3.4.3 -v
/tmp/python-build.20160329101407.86466 ~/.pyenv/versions
Downloading Python-3.4.3.tgz...
-> https://www.python.org/ftp/python/3.4.3/Python-3.4.3.tgz
curl: (7) couldn't connect to host
error: failed to download Python-3.4.3.tar.gz

BUILD FAILED (RedHatEnterpriseServer 6.4 using python-build 20160130)

**Comment by joshfriend** [comment]
I think you also need to set:

```shell
export PYTHON_BUILD_CACHE_PATH="$PYENV_ROOT/cache"
```

**Comment by ironicChen** [comment]
still dosen't work...

[root@cnsz22vl0279:/root/.pyenv/versions]#echo $PYTHON_BUILD_CACHE_PATH
/root/.pyenv/cache
[root@cnsz22vl0279:/root/.pyenv/versions]#ll /root/.pyenv/cache
total 19100
-rw-r--r-- 1 root root 19554643 Mar 28 14:23 Python-3.4.3.tgz
[root@cnsz22vl0279:/root/.pyenv/versions]#pyenv install 3.4.3 -v
/tmp/python-build.20160329105326.128025 ~/.pyenv/versions
Downloading Python-3.4.3.tgz...
-> https://www.python.org/ftp/python/3.4.3/Python-3.4.3.tgz
curl: (7) couldn't connect to host
error: failed to download Python-3.4.3.tar.gz

BUILD FAILED (RedHatEnterpriseServer 6.4 using python-build 20160130)

**Comment by yyuu** [comment]
You don't have to explicitly declare `PYTHON_BUILD_CACHE_PATH` since it's defined as the default value.

https://github.com/yyuu/pyenv/blob/v20160310/plugins/python-build/bin/pyenv-install#L183

According to impl, `python-build` (the backend of `pyenv install`) will ignore cached tarball if it doesn't have proper checksum.

https://github.com/yyuu/pyenv/blob/v20160310/plugins/python-build/bin/python-build#L431-L447

Please make sure if the cached archive has proper SHA256 checksum declared in the build definition of 3.4.3.

https://github.com/yyuu/pyenv/blob/v20160310/plugins/python-build/share/python-build/3.4.3#L4

**Comment by ironicChen** [comment]
thanks for your helping!
I found that the expected file name is "Python-3.4.3.tar.gz" but my file name is Python-3.4.3.tgz......
I down it from url https://www.python.org/ftp/python/3.4.3/Python-3.4.3.tgz from the ouput of "pyenv install"
now it's done~
thanks again~

**Comment by yufeiminds** [comment]
I downloaded it from https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz, re-zip as `Python-2.7.11.tar.gz`, but it still doesn't work. 

Any one has the same problem?
Thanks~

**Comment by ironicChen** [comment]
@yufeiminds 
try to rename the file directly instead of re-zip~

**Comment by neverUseThisName** [comment]
Does this still work in 2019?

**Comment by ironicChen** [comment]
> Does this still work in 2019?

yes, it works
