### ISSUE TITLE
CRLF everywhere

### ISSUE THREAD

**Issue by abstrus** [yyuu/pyenv#564]
There are `\r` everywhere in these scripts, leading to

```
$ pyenv
: No such file or directory
```

Total 547 files with DOS line endings (I got the number from the following command)

```
find ~/.pyenv -not -type d -exec file "{}" ";" | grep CRLF | wc -l
```

**Comment by joshfriend** [comment]
Did you look at what files had these line endings? I ran that command and all the files it found were from inside the `lib/` directories of the installed python versions.

Are you on windows? If so, make sure that `core.autocrlf` is not `true`. Otherwise, git will make the line endings DOS on checkout.

**Comment by abstrus** [comment]
In facts, I am on linux and for some reason I had `autocrlf`set to `true`.  This is embarrassing.
