### ISSUE TITLE
Failed to install Anaconda3-4.0.0

### ISSUE THREAD

**Issue by tasugi** [yyuu/pyenv#597]
I tried to install Anaconda, but failed.
```
$ pyenv install anaconda3-4.0.0 
Downloading Anaconda3-4.0.0-Linux-x86_64.sh...
-> https://repo.continuum.io/archive/Anaconda3-4.0.0-Linux-x86_64.sh
error: failed to download Anaconda3-4.0.0-Linux-x86_64.sh

BUILD FAILED (Ubuntu 16.04 using python-build 20160509)

Inspect or clean up the working tree at /tmp/python-build.20160511160320.2542
Results logged to /tmp/python-build.20160511160320.2542.log

Last 10 log lines:
/tmp/python-build.20160511160320.2542 ~
curl: (56) GnuTLS recv error (-9): A TLS packet with unexpected length was received.
```
Would you check this?

**Comment by thomasjo** [comment]
Just try again — the download failed, which was likely caused by a hiccup on either end of the connection. This is not a problem with pyenv.

**Comment by tasugi** [comment]
I tried several times. However always failed.

**Comment by thomasjo** [comment]
If you look at the error message, something is definitely wrong. Likely on your end since you're getting TLS certificate errors (issue specific to SSL handshake I think) which I am unable to reproduce. The certificate on repo.continuum.io seems valid on my end.

If you have `wget` installed, you might be able to manually work around your problem (until you fix your environment/certificate problem properly) by executing e.g.

``` sh
$ wget -P $(pyenv root)/cache https://repo.continuum.io/archive/Anaconda3-4.0.0-Linux-x86_64.sh
```

Then you should be able to run `pyenv install anaconda3-4.0.0` without problems, assuming that the manual download trick above succeeded.
