### ISSUE TITLE
crashing anaconda envs on activation

### ISSUE THREAD

**Issue by jmccormac01** [yyuu/pyenv#662]
Hi, I am trying to install [astroconda](https://github.com/astroconda/astroconda) for work. I manage my python versions with pyenv. I've installed a specific installation of anaconda-4.0.0 with pyenv so I can set up an astroconda env. When I follow the instructions on the astroconda RTD page and then try to activate the env with 

```
source activate astroconda
```

it crashes the terminal window completely. At first I thought this might be an astroconda issue, but now I am not sure. I tried making a throwaway env as suggested to my [issue](https://github.com/astroconda/astroconda/issues/14) on the astroconda repo. When I do this the terminal still crashes. I think the modified activate script in .shims might be causing the problem? 

Any help would be great, thanks. Below is a screen shot of the terminal output right before it dies. 
Cheers,
James

<img width="1340" alt="screen shot 2016-07-22 at 12 54 31" src="https://cloud.githubusercontent.com/assets/1912007/17073188/56f36d4a-5066-11e6-839c-062aaf191c90.png">

**Comment by nicktimko** [comment]
What do you mean by "crashes"? Freezes? Does Ctrl-C (SIGTERM) or Ctrl-D (EOF) bring it back?

This is probably an issue with Anaconda and/or your shell (what shell are you using?); `source` might be doing something strange like interpreting its arguments as a command to evaluate, which is why Anaconda is printing that error that tells you to use `source` even though you did.

**Comment by yyuu** [comment]
I could not reproduce the issue.

It seems that one of astroconda's dependencies install custom profile script. Though it just worked fine for me at least.

```sh
% pyenv sh-activate miniconda3-4.0.5/envs/astroconda
unset PYENV_VIRTUAL_ENV;
unset VIRTUAL_ENV;
if [ -n "${_OLD_VIRTUAL_PATH}" ]; then
  export PATH="${_OLD_VIRTUAL_PATH}";
  unset _OLD_VIRTUAL_PATH;
fi;
if [ -n "${_OLD_VIRTUAL_PYTHONHOME}" ]; then
  export PYTHONHOME="${_OLD_VIRTUAL_PYTHONHOME}";
  unset _OLD_VIRTUAL_PYTHONHOME;
fi;
if [ -n "${_OLD_VIRTUAL_PS1}" ]; then
  export PS1="${_OLD_VIRTUAL_PS1}";
  unset _OLD_VIRTUAL_PS1;
fi;
if declare -f deactivate 1>/dev/null 2>&1; then
  unset -f deactivate;
fi;
export PYENV_VERSION="miniconda3-4.0.5/envs/astroconda";
export PYENV_ACTIVATE_SHELL=1;
export PYENV_VIRTUAL_ENV="/home/yyuu/.pyenv/versions/miniconda3-4.0.5/envs/astroconda";
export VIRTUAL_ENV="/home/yyuu/.pyenv/versions/miniconda3-4.0.5/envs/astroconda";
export CONDA_DEFAULT_ENV="astroconda";
. "/home/yyuu/.pyenv/versions/miniconda3-4.0.5/envs/astroconda/etc/conda/activate.d/webbpsf-data.sh";
```

**Comment by pocin** [comment]
Hi, I have exactly the same issue. I ran exactly these commands

1. `$ brew install pyenv`
2. add `PYENV_ROOT=/usr/local/var/pyenv/` and `if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi` (in this order) to .zshrc
3. run `$ conda create -n data requests` and `pyenv local miniconda3-latest` and `pyenv global miniconda3-latest`. 
4. Restart shell.
5. At this point `$ which activate` outputs `/usr/local/var/pyenv/shims/activate`. and  
```
$ pyenv versions
  system
* miniconda3-latest (set by /Users/pocin/.python-version)
  miniconda3-latest/envs/data
```
6. and the problem: `$source activate data` exits the terminal with the message `"Error: activate must be sourced. Run source activate envname instead of activate envname.`
7. `$ which source` yields `source: shell built-in command`

If i cd into `/usr/local/var/pyenv/versions/miniconda3-latest/bin` and run `$source activate data` the env gets activated and it works. I suppose there is a problem with the activate shim?
Here are the contents of `/usr/local/var/pyenv/shims/activate`

```bash
#!/usr/bin/env bash
set -e
[ -n "$PYENV_DEBUG" ] && set -x

program="${0##*/}"
if [[ "$program" = "python"* ]]; then
  for arg; do
    case "$arg" in
    -c* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export PYENV_FILE_ARG="$arg"
        break
      fi
      ;;
    esac
  done
fi

export PYENV_ROOT="/usr/local/var/pyenv"
exec "/usr/local/Cellar/pyenv/1.0.6/libexec/pyenv" exec "$program" "$@"
```
I will happily provide more info

**Comment by yyuu** [comment]
@pocin the `activate` script of `virtualenv` and `anaconda` will not work without trick in pyenv since the shim script generated by pyenv is created for executables 😞 Even if the `activate` script works with pyenv, because the script will manage `$PATH` of user's interactive shell, unfortunately it won't work well with pyenv's shim scripts.

As a workaround, I've prepared support for Anaconda style activation in pyenv-virtualenv. I'd recommend Anaconda users to install pyenv-virtualenv if they'd like to use pyenv style versioning with conda's environments. Please give it a try.

https://github.com/yyuu/pyenv-virtualenv/tree/a3bc42cb93c5758ae967b4637829826800053689#anaconda-and-miniconda

**Comment by pocin** [comment]
@yyuu oh thanks! I'll give it a shot :) I had a feeling it was not a bug, but I just could not find any mention of pyenv-virtualenv in the docs. Perhaps a small note/link could be added?
Thanks for your good work 👍
