### ISSUE TITLE
Installation with fish on README or wiki

### ISSUE THREAD

**Issue by shigemk2** [yyuu/pyenv#795]
Do you have any plan to add how to install pyenv with fish on README or wiki?

```
setenv PATH "$HOME/.pyenv/bin" $PATH
eval (pyenv init - fish)
```

https://github.com/yyuu/pyenv/issues/32#issuecomment-22705181

**Comment by yyuu** [comment]
I don't have any plan to work for fish since I'm not an active user of the shell. If you think fish users need some notes, please open PRs or edit wiki by yourself.

BTW, I guess it'd be better add 'status --is-interactive' in your fish configuration.

https://github.com/yyuu/pyenv/blob/master/libexec/pyenv-init#L73
