### ISSUE TITLE
install virtualenv in project directory

### ISSUE THREAD

**Issue by marcosfede** [yyuu/pyenv#802]
Hi, I wonder if its possible to install the virtualenv on the projects directory instead of installing it in .pyenv/versions .
there are many tools that assume you have your venvs on the same directory like vscode. 

Is there any flag I can add to `pyenv virtualenv` to do this?

**Comment by yyuu** [comment]
You can just create virtualenv in any location. To use it from pyenv, create symlink to the environment in ~/.pyenv/versions

**Comment by vc5** [comment]
In VS Code,you can just use `ctrl +p` then type `python:select wordspace interpreter`

**Comment by cirosantilli** [comment]
I wish there would be a more "managed" way of doing this, rather than forcing users to make symlinks.

Does it work if you just install `pip install virtualenv` from inside `pyenv`?

**Comment by grayaii** [comment]
Ugh. We have a jenkins machine that runs multiple jobs at the same time on the same machine, each creating/destroying a same-named virtualenv.  This stomps on each other, and thus causes build failures.  It would be nice if pyenv created the virtualenv local to the jenkins workspace, so that they are self contained within the workspace of the job.  Looking at this post, I THINK you can use "virtualenv" (not pyenv virtualenv)... https://stackoverflow.com/questions/30407446/pyenv-choose-virtualenv-directory

**Comment by russellvt** [comment]
Yes @grayaii, you **_can_** use just straight virtualenv, but then you're going to get in to another "chicken and egg" problem, and potentially induce confusion with "which virtualenv" - not to mention, you'd need to increase the ability to reasonably control the Python versions (assuming you're in-need of testing multiple versions of Python).

For me, I just use scripts within Jenkins that add-in unique variables, such as the build name or number to name the pyenv, when it's created. It works "well enough," particularly if you're routinely destroying the environments following the build.

**Comment by vedal** [comment]
I would also really like to specify install directory when creating a new venv with pyenv.

**Comment by grayaii** [comment]
@russellvt your suggestion of adding build name and build number made it work "well enough".  It still sporadically fails when creating unique pyenv virtualenvs at the same time.  We get these weird errors when running pip installs of the same package at the same time, but in different virtualenvs.

```
IOError: [Errno 2] No such file or directory: '/opt/pyenv/install_dir/versions/2.7.14/lib/python2.7/site-packages/configparser-4.0.2.dist-info/RECORD.pip'
```

But at least it's not failing

**Comment by lowercase00** [comment]
Moved to Pyenv to try to manage different versions, but find myself really struggling with the complexity it brings. Always use `.venv` for the name of my venvs, but get that it "already exists", since it's creating it in .pyenv/versions. I would rather have it inside my workspace folder, so I can delete, recreate, and choose the VSCode language server. Since i've made the switch been struggling with static type checking, and a lot more in VSCode. Have to confess I don't really understand the logic behind this decision - `poetry` went through something similar and quickly addressed the issue. Is there any news on this front?

**Comment by tvalentyn** [comment]
Thanks for sharing your experience, @grayaii 

> Ugh. We have a jenkins machine that runs multiple jobs at the same time on the same machine, each creating/destroying a same-named virtualenv.

I was also thinking about using pyenv on Jenkins, and I'd like temporary environments be created under `workspace/`, which can be cleaned up between the runs. Having the pyenv environment created outside the workspace means that botched runs could leave created environments behind, potentially filling up the space on the Jenkins worker, so we'd have find a way to clean them up periodically.

> It still sporadically fails when creating unique pyenv virtualenvs at the same time.
What is the explanation for these failures?
